{"name": "test_cont_fraction_failed[239-30-result0]", "status": "failed", "statusDetails": {"message": "AssertionError: assert [7, 1, 29] == [7, 1, 30]\n  At index 2 diff: 29 != 30\n  Use -v to get the full diff", "trace": "number = 239, divider = 30, result = [7, 1, 30]\n\n    @allure.feature(\"f2\")\n    @allure.severity(allure.severity_level.TRIVIAL)\n    @pytest.mark.parametrize(\"number, divider, result\", [(239, 30, [7, 1, 30])])\n    def test_cont_fraction_failed(number, divider, result):\n>       assert list(cont_fraction(number, divider)) == result\nE       assert [7, 1, 29] == [7, 1, 30]\nE         At index 2 diff: 29 != 30\nE         Use -v to get the full diff\n\ntest_task01.py:14: AssertionError"}, "parameters": [{"name": "number", "value": "239"}, {"name": "divider", "value": "30"}, {"name": "result", "value": "[7, 1, 30]"}], "start": 1618397798153, "stop": 1618397798154, "uuid": "692f325c-7484-4815-a8d3-4e5f6fbcadbf", "historyId": "1d1d8f8763b79b012df6a56ddd027b40", "testCaseId": "5234d73e4db00176d47c9b4d2d5376f4", "fullName": "test_task01#test_cont_fraction_failed", "labels": [{"name": "severity", "value": "trivial"}, {"name": "feature", "value": "f2"}, {"name": "suite", "value": "test_task01"}, {"name": "host", "value": "C02ZK1WXLVDL"}, {"name": "thread", "value": "56488-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_task01"}]}